<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>VisionUpdater</AssemblyName>
    <RootNamespace>VisionInspectionApp.Updater</RootNamespace>
    <ApplicationIcon>..\VisionInspectionApp.UI\Assets\cms-vina-vision-system.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\VisionInspectionApp.UI\Assets\cms-vina-vision-system.ico" />
  </ItemGroup>

</Project>
