<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x86;AnyCPU;x64</Platforms>
    <ApplicationIcon>..\VisionInspectionApp.UI\Assets\cms-vina-vision-system.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
