<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\VisionInspectionApp.UI\Assets\cms-vina-vision-system.ico</ApplicationIcon>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisionInspectionApp.Application\VisionInspectionApp.Application.csproj" />
    <ProjectReference Include="..\VisionInspectionApp.Models\VisionInspectionApp.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

</Project>
